lib/relay_ui_web/router.ex
defmodule RelayUiWeb.Router do
  use RelayUiWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
#    plug :put_root_layout, {RelayUiWeb.LayoutView, :root}
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  if Mix.env() == :dev do
    forward "/sent-emails", Bamboo.SentEmailViewerPlug
  end

  scope "/", RelayUiWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/admin", PageController, :admin

    resources "/login-requests", LoginRequestController,
      only: [:create, :new, :show],
      param: "token"

    resources "/sessions", SessionController, only: [:delete], singleton: true
  end

  # Other scopes may use custom stacks.
  # scope "/api", RelayUiWeb do
  #   pipe_through :api
  # end
end

lib/relay_ui_web/templates/page/index.html.eex
<div class="container">
  <%= if logged_in?(@conn) do %>
    <%= link "Log out", to: Routes.session_path(@conn, :delete), method: :delete %>
  <% else %>
    <%= link "Log in", to: Routes.login_request_path(@conn, :new) %>
  <% end %>
  testing
</div>

lib/relay_ui_web/templates/page/relay_view.html.leex
<div class="container">
  <%= for {key, value} <- @relay_list do %>
  <div class="inline">
    <%= key %>
    <input checked="checked" id=<%=key%> name="relay[<%= key%>]" type="checkbox" value="on">
    <div>
      <% {_, lid_state} = value["lid"] %>
      <% {_, clamp_state} = value["clamp"] %>
      <% {_, sample_state} = value["sample"] %>
      <%= if lid_state == :on do %>
      <button class="button button-black" phx-click="off"
                                          phx-value-relay="<%= key%>.lid">
      <% else %>
      <button class="button button-outline" phx-click="on"
                                            phx-value-relay="<%= key%>.lid">
      <% end %>Lid</button>

      <%= if clamp_state == :on do %>
      <button class="button button-black" phx-click="off"
                                          phx-value-relay="<%= key%>.clamp">
      <% else %>
      <button class="button button-outline" phx-click="on"
                                            phx-value-relay="<%= key%>.clamp">
      <% end %>Clamp</button>

      <%= if sample_state == :on do %>
      <button class="button button-black" phx-click="off"
                                          phx-value-relay="<%=key%>.sample">
      <% else %>
      <button class="button button-outline" phx-click="on"
                                            phx-value-relay="<%= key%>.sample">
      <% end %>Sample</button>
    </div>
  </div>
  <% end %>
</div>